name: Cross-platform CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: luojiyin1987/cross-platform-ci/.github/workflows/build.yml@bf2e271adedb396d0fd0790ffe39207740b17e99
    with:
      package: ./cmd/cxq
      binary-name: cxq
